### ISSUE TITLE
Why not use isprint() ?

### ISSUE THREAD

**Issue by perror** [jashbin/triaging-binaries-toolkit#1]
https://github.com/jashbin/triaging-binaries-toolkit/blob/651264a11006e9e23025070a81222702422794ac/src/elf_manager.c#L73
Why not using the `isprint()` function from standard C library ?

**Comment by CPietJa** [comment]
Thx for the reminder.
I did not no that the std C lib has this function, I did not search, it was a function I create when doing test on the libelf.
I will make the change asap.

**Comment by perror** [comment]
Well, check first that the libc function fit your need. But, I believe so (and, there is no hurry!). The point here is to avoid to recode (and maintain) what is already existing.
