### ISSUE TITLE
Why `main` and not `master` ?

### ISSUE THREAD

**Issue by perror** [jashbin/triaging-binaries-toolkit#3]
I noticed that your main branch is called `main`, the standard way would be to call it `master`.

This is not really a problem, but it tends to confuse people when you escape from the standard way of doing.

Anyway, I can perfectly go with it, if you want to keep it this way. As you wish.

**Comment by CPietJa** [comment]
It was due to github that replace master by main

**Comment by perror** [comment]
Ah, so this is the standard way on Github now... So, lets stick to it. 
Finally, this stupid flame war about the master/slave did really change a few things... Yet, I am not sure it helps to fight intolerance and hate at all. ;-)
Anyway, keep it like this then. You can close this issue.
